version: "3"
services:
  app:
    image: node:latest
    command: bash -c "npm ci && npm run test"
    volumes:
      - "./:/code"
    working_dir: "/code"
    depends_on:
      - error
  error:
    image: node:latest
    command: bash -c "node lib/throwError"