version: "3"
services:
  app:
    image: node:latest
    command: bash -c "npm ci && npm run test"
    volumes:
      - "./typedoc:/code"
    working_dir: "/code"
  # error:
  #   image: node:latest
  #   command: bash -c "node lib/throwError"
