name: release

permissions:
  contents: write

on:
  push:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: docker compose up --abort-on-container-exit
